(function() {
‘use strict’;

/* ===========================
Data Model
=========================== */

const DATA = {
eras: [
{ id: 1, name: ‘Early Islam’, slug: ‘early-islam’, period: ‘610-661 CE’, color: ‘#1a5f5f’, description: ‘The foundational period beginning with revelation and establishment of the Muslim community.’ },
{ id: 2, name: ‘Rashidun Caliphate’, slug: ‘rashidun’, period: ‘632-661 CE’, color: ‘#2a7f7f’, description: ‘The era of the four rightly-guided caliphs following Prophet Muhammad.’ },
{ id: 3, name: ‘Umayyad Caliphate’, slug: ‘umayyad’, period: ‘661-750 CE’, color: ‘#c9943a’, description: ‘First major Islamic dynasty with capital in Damascus, expansion across three continents.’ },
{ id: 4, name: ‘Abbasid Caliphate’, slug: ‘abbasid’, period: ‘750-1258 CE’, color: ‘#1a5f5f’, description: ‘Golden age of Islamic civilization centered in Baghdad.’ },
{ id: 5, name: ‘Fatimid Caliphate’, slug: ‘fatimid’, period: ‘909-1171 CE’, color: ‘#2a7f7f’, description: ‘Ismaili Shia dynasty ruling North Africa and parts of the Middle East.’ },
{ id: 6, name: ‘Seljuk Empire’, slug: ‘seljuk’, period: ‘1037-1194 CE’, color: ‘#c9943a’, description: ‘Turkic empire that dominated much of the Islamic world.’ },
{ id: 7, name: ‘Ayyubid Dynasty’, slug: ‘ayyubid’, period: ‘1171-1260 CE’, color: ‘#1a5f5f’, description: ‘Kurdish dynasty founded by Saladin, known for confronting Crusaders.’ },
{ id: 8, name: ‘Mamluk Sultanate’, slug: ‘mamluk’, period: ‘1250-1517 CE’, color: ‘#2a7f7f’, description: ‘Slave-soldier dynasty ruling Egypt and Syria.’ },
{ id: 9, name: ‘Mongol Invasions’, slug: ‘mongol’, period: ‘1206-1368 CE’, color: ‘#c9943a’, description: ‘Period of Mongol conquests and eventual conversion to Islam.’ },
{ id: 10, name: ‘Ottoman Empire’, slug: ‘ottoman’, period: ‘1299-1922 CE’, color: ‘#1a5f5f’, description: ‘Longest-lasting Islamic empire, centered in Anatolia and expanding across three continents.’ },
{ id: 11, name: ‘Safavid Empire’, slug: ‘safavid’, period: ‘1501-1736 CE’, color: ‘#2a7f7f’, description: ‘Persian empire that established Twelver Shiism as state religion.’ },
{ id: 12, name: ‘Mughal Empire’, slug: ‘mughal’, period: ‘1526-1857 CE’, color: ‘#c9943a’, description: ‘Islamic empire in the Indian subcontinent known for cultural synthesis.’ },
{ id: 13, name: ‘Modern Period’, slug: ‘modern’, period: ‘1800-Present’, color: ‘#1a5f5f’, description: ‘Era of colonialism, independence movements, and contemporary Islamic societies.’ }
],

```
themes: [
  { id: 1, name: 'Political History', slug: 'political', icon: '⚖', description: 'Dynasties, caliphates, governance systems, and political developments.' },
  { id: 2, name: 'Intellectual History', slug: 'intellectual', icon: '📚', description: 'Scholarly traditions, schools of thought, and intellectual movements.' },
  { id: 3, name: 'Science & Philosophy', slug: 'science', icon: '🔬', description: 'Scientific achievements, philosophical traditions, and innovations.' },
  { id: 4, name: 'Society & Culture', slug: 'culture', icon: '🎭', description: 'Social structures, cultural practices, arts, and daily life.' },
  { id: 5, name: 'Military History', slug: 'military', icon: '⚔', description: 'Battles, conquests, military strategies, and conflicts.' },
  { id: 6, name: 'Architecture & Arts', slug: 'architecture', icon: '🕌', description: 'Architectural achievements, artistic traditions, and cultural monuments.' },
  { id: 7, name: 'Trade & Economy', slug: 'economy', icon: '💰', description: 'Trade networks, economic systems, and commercial developments.' },
  { id: 8, name: 'Religious Scholarship', slug: 'religious', icon: '📖', description: 'Islamic jurisprudence, theology, hadith sciences, and Quranic exegesis.' }
],

events: [
  { id: 1, name: 'First Revelation', year: 610, eraId: 1, themeIds: [8], summary: 'Prophet Muhammad received first revelation in Cave Hira.' },
  { id: 2, name: 'Migration to Medina', year: 622, eraId: 1, themeIds: [1, 4], summary: 'Hijra marks beginning of Islamic calendar and establishment of Muslim community.' },
  { id: 3, name: 'Battle of Badr', year: 624, eraId: 1, themeIds: [5], summary: 'First major military victory for Muslims against Meccan forces.' },
  { id: 4, name: 'Battle of Uhud', year: 625, eraId: 1, themeIds: [5], summary: 'Significant battle testing Muslim resolve and unity.' },
  { id: 5, name: 'Treaty of Hudaybiyyah', year: 628, eraId: 1, themeIds: [1], summary: 'Pivotal peace treaty between Muslims and Meccans.' },
  { id: 6, name: 'Conquest of Mecca', year: 630, eraId: 1, themeIds: [1, 5], summary: 'Peaceful conquest of Mecca, cleansing of Kaaba.' },
  { id: 7, name: 'Farewell Sermon', year: 632, eraId: 1, themeIds: [8], summary: 'Prophet Muhammad delivered final sermon establishing key principles.' },
  { id: 8, name: 'Death of Prophet Muhammad', year: 632, eraId: 1, themeIds: [8], summary: 'Passing of the Prophet, transition to Rashidun era.' },
  { id: 9, name: 'Abu Bakr Elected Caliph', year: 632, eraId: 2, themeIds: [1], summary: 'First caliph chosen through consultation of companions.' },
  { id: 10, name: 'Ridda Wars', year: 632, eraId: 2, themeIds: [5], summary: 'Series of campaigns to consolidate Arabian Peninsula under Islam.' },
  { id: 11, name: 'Compilation of Quran', year: 633, eraId: 2, themeIds: [8], summary: 'Written compilation ordered by Abu Bakr to preserve revelation.' },
  { id: 12, name: 'Battle of Yarmouk', year: 636, eraId: 2, themeIds: [5], summary: 'Decisive victory against Byzantine Empire in Syria.' },
  { id: 13, name: 'Conquest of Jerusalem', year: 637, eraId: 2, themeIds: [1, 5], summary: 'Umar ibn al-Khattab peacefully receives Jerusalem.' },
  { id: 14, name: 'Battle of Qadisiyyah', year: 636, eraId: 2, themeIds: [5], summary: 'Major victory against Sasanian Persian Empire.' },
  { id: 15, name: 'Conquest of Egypt', year: 642, eraId: 2, themeIds: [1, 5], summary: 'Strategic victory bringing Egypt under Islamic rule.' },
  { id: 16, name: 'Assassination of Umar', year: 644, eraId: 2, themeIds: [1], summary: 'Second caliph martyred, succeeded by Uthman.' },
  { id: 17, name: 'Standard Quran Codex', year: 650, eraId: 2, themeIds: [8], summary: 'Uthman standardized Quranic text across Muslim lands.' },
  { id: 18, name: 'First Fitna', year: 656, eraId: 2, themeIds: [1, 5], summary: 'Civil war following assassination of Uthman.' },
  { id: 19, name: 'Battle of Camel', year: 656, eraId: 2, themeIds: [5], summary: 'Battle during civil strife in early Muslim community.' },
  { id: 20, name: 'Battle of Siffin', year: 657, eraId: 2, themeIds: [5], summary: 'Major battle between Ali and Muawiya forces.' },
  { id: 21, name: 'Arbitration at Adhruh', year: 658, eraId: 2, themeIds: [1], summary: 'Attempt to resolve conflict through negotiation.' },
  { id: 22, name: 'Assassination of Ali', year: 661, eraId: 2, themeIds: [1], summary: 'Fourth caliph martyred, end of Rashidun period.' },
  { id: 23, name: 'Umayyad Dynasty Begins', year: 661, eraId: 3, themeIds: [1], summary: 'Muawiya establishes hereditary caliphate in Damascus.' },
  { id: 24, name: 'Tragedy of Karbala', year: 680, eraId: 3, themeIds: [1, 8], summary: 'Martyrdom of Husayn ibn Ali, profound impact on Islamic history.' },
  { id: 25, name: 'Conquest of North Africa', year: 698, eraId: 3, themeIds: [1, 5], summary: 'Extension of Islamic rule across Maghreb.' },
  { id: 26, name: 'Islamic Conquest of Sind', year: 711, eraId: 3, themeIds: [1, 5], summary: 'Muslim rule established in Indian subcontinent.' },
  { id: 27, name: 'Islamic Spain Established', year: 711, eraId: 3, themeIds: [1, 5], summary: 'Tariq ibn Ziyad crosses into Iberian Peninsula.' },
  { id: 28, name: 'Battle of Tours', year: 732, eraId: 3, themeIds: [5], summary: 'Muslim advance into Western Europe halted in France.' },
  { id: 29, name: 'Abbasid Revolution', year: 750, eraId: 4, themeIds: [1], summary: 'Overthrow of Umayyads, establishment of Abbasid Caliphate.' },
  { id: 30, name: 'Foundation of Baghdad', year: 762, eraId: 4, themeIds: [1, 6], summary: 'Caliph al-Mansur establishes new capital as center of learning.' },
  { id: 31, name: 'House of Wisdom Founded', year: 830, eraId: 4, themeIds: [2, 3], summary: 'Major library and translation center established in Baghdad.' },
  { id: 32, name: 'Translation Movement Peak', year: 850, eraId: 4, themeIds: [2, 3], summary: 'Massive translation of Greek, Persian, and Indian works.' },
  { id: 33, name: 'Al-Khwarizmi Algebra', year: 820, eraId: 4, themeIds: [3], summary: 'Foundation of algebra as mathematical discipline.' },
  { id: 34, name: 'Samarra Capital', year: 836, eraId: 4, themeIds: [1, 6], summary: 'Temporary move of Abbasid capital demonstrating architectural ambition.' },
  { id: 35, name: 'Battle of Talas', year: 751, eraId: 4, themeIds: [5, 7], summary: 'Victory against Tang China, spread of papermaking to Islamic world.' },
  { id: 36, name: 'Fatimid Caliphate Founded', year: 909, eraId: 5, themeIds: [1, 8], summary: 'Ismaili Shia dynasty established in North Africa.' },
  { id: 37, name: 'Conquest of Egypt by Fatimids', year: 969, eraId: 5, themeIds: [1, 5], summary: 'Fatimids establish control over Egypt.' },
  { id: 38, name: 'Cairo Founded', year: 969, eraId: 5, themeIds: [1, 6], summary: 'New capital al-Qahira established by Fatimids.' },
  { id: 39, name: 'Al-Azhar Mosque Founded', year: 970, eraId: 5, themeIds: [6, 8], summary: 'Establishment of one of worlds oldest universities.' },
  { id: 40, name: 'Seljuk Conquest of Baghdad', year: 1055, eraId: 6, themeIds: [1, 5], summary: 'Turkic Seljuks become protectors of Abbasid caliphs.' },
  { id: 41, name: 'Battle of Manzikert', year: 1071, eraId: 6, themeIds: [5], summary: 'Decisive Seljuk victory over Byzantines opening Anatolia.' },
  { id: 42, name: 'First Crusade', year: 1096, eraId: 6, themeIds: [5], summary: 'European Christian military campaign to reclaim Holy Land.' },
  { id: 43, name: 'Capture of Jerusalem by Crusaders', year: 1099, eraId: 6, themeIds: [1, 5], summary: 'Crusaders take Jerusalem, establishing Latin Kingdom.' },
  { id: 44, name: 'Nizamiyya Madrasa Founded', year: 1065, eraId: 6, themeIds: [2, 8], summary: 'Influential educational institutions established by Nizam al-Mulk.' },
  { id: 45, name: 'Saladin Founds Ayyubid Dynasty', year: 1171, eraId: 7, themeIds: [1], summary: 'Kurdish general establishes dynasty unifying Egypt and Syria.' },
  { id: 46, name: 'Battle of Hattin', year: 1187, eraId: 7, themeIds: [5], summary: 'Decisive victory by Saladin over Crusader forces.' },
  { id: 47, name: 'Recapture of Jerusalem', year: 1187, eraId: 7, themeIds: [1, 5], summary: 'Saladin peacefully retakes Jerusalem from Crusaders.' },
  { id: 48, name: 'Third Crusade', year: 1189, eraId: 7, themeIds: [5], summary: 'European response led by Richard I, resulted in treaty.' },
  { id: 49, name: 'Mamluk Sultanate Established', year: 1250, eraId: 8, themeIds: [1], summary: 'Slave-soldier class seizes power in Egypt and Syria.' },
  { id: 50, name: 'Battle of Ain Jalut', year: 1260, eraId: 8, themeIds: [5], summary: 'Mamluks decisively defeat Mongols, halting their advance.' },
  { id: 51, name: 'Fall of Baghdad to Mongols', year: 1258, eraId: 9, themeIds: [1, 5], summary: 'Hulagu Khan sacks Baghdad, ending Abbasid Caliphate in Iraq.' },
  { id: 52, name: 'Conversion of Golden Horde', year: 1313, eraId: 9, themeIds: [1, 8], summary: 'Mongol khanate officially adopts Islam.' },
  { id: 53, name: 'Ibn Taymiyyah Trial', year: 1306, eraId: 8, themeIds: [2, 8], summary: 'Influential scholar faces opposition for strict interpretations.' },
  { id: 54, name: 'Ottoman State Founded', year: 1299, eraId: 10, themeIds: [1], summary: 'Osman I establishes dynasty that becomes major empire.' },
  { id: 55, name: 'Conquest of Constantinople', year: 1453, eraId: 10, themeIds: [1, 5], summary: 'Mehmed II captures Byzantine capital, renamed Istanbul.' },
  { id: 56, name: 'Battle of Mohacs', year: 1526, eraId: 10, themeIds: [5], summary: 'Ottoman victory bringing Hungary under their control.' },
  { id: 57, name: 'Siege of Vienna', year: 1529, eraId: 10, themeIds: [5], summary: 'Ottoman expansion into Central Europe temporarily checked.' },
  { id: 58, name: 'Battle of Lepanto', year: 1571, eraId: 10, themeIds: [5], summary: 'Naval defeat by Holy League, checking Ottoman Mediterranean power.' },
  { id: 59, name: 'Suleymaniye Mosque Completed', year: 1557, eraId: 10, themeIds: [6], summary: 'Architectural masterpiece by Mimar Sinan in Istanbul.' },
  { id: 60, name: 'Safavid Dynasty Founded', year: 1501, eraId: 11, themeIds: [1, 8], summary: 'Ismail I establishes Twelver Shiism as state religion of Persia.' },
  { id: 61, name: 'Battle of Chaldiran', year: 1514, eraId: 11, themeIds: [5], summary: 'Ottoman victory over Safavids establishing border.' },
  { id: 62, name: 'Shah Abbas Reforms', year: 1587, eraId: 11, themeIds: [1, 4], summary: 'Major administrative and military reforms strengthen empire.' },
  { id: 63, name: 'Isfahan Rebuilt', year: 1598, eraId: 11, themeIds: [6], summary: 'Capital transformed into architectural marvel.' },
  { id: 64, name: 'First Battle of Panipat', year: 1526, eraId: 12, themeIds: [5], summary: 'Babur establishes Mughal rule in India.' },
  { id: 65, name: 'Akbar Reign Begins', year: 1556, eraId: 12, themeIds: [1], summary: 'Greatest Mughal emperor known for administrative genius and tolerance.' },
  { id: 66, name: 'Din-i-Ilahi Proclaimed', year: 1582, eraId: 12, themeIds: [8], summary: 'Akbar attempts syncretic religious movement.' },
  { id: 67, name: 'Taj Mahal Construction', year: 1632, eraId: 12, themeIds: [6], summary: 'Shah Jahan builds iconic mausoleum for his wife.' },
  { id: 68, name: 'Aurangzeb Reign', year: 1658, eraId: 12, themeIds: [1], summary: 'Last great Mughal emperor, empire reaches maximum extent.' },
  { id: 69, name: 'Battle of Plassey', year: 1757, eraId: 13, themeIds: [1, 5], summary: 'British East India Company defeats Bengal, beginning colonial dominance.' },
  { id: 70, name: 'Wahhabi Movement', year: 1744, eraId: 13, themeIds: [8], summary: 'Reform movement in Arabia emphasizing Quranic monotheism.' },
  { id: 71, name: 'Napoleon Egypt Campaign', year: 1798, eraId: 13, themeIds: [1, 5], summary: 'French invasion sparks modernization debates in Muslim world.' },
  { id: 72, name: 'Muhammad Ali Egypt', year: 1805, eraId: 13, themeIds: [1], summary: 'Albanian commander modernizes Egypt with Western techniques.' },
  { id: 73, name: 'Tanzimat Reforms', year: 1839, eraId: 13, themeIds: [1, 4], summary: 'Ottoman modernization and administrative reorganization.' },
  { id: 74, name: 'Indian Rebellion', year: 1857, eraId: 13, themeIds: [1, 5], summary: 'Uprising against British rule, end of Mughal Empire.' },
  { id: 75, name: 'Opening of Suez Canal', year: 1869, eraId: 13, themeIds: [7], summary: 'Strategic waterway with major geopolitical implications.' },
  { id: 76, name: 'British Egypt Occupation', year: 1882, eraId: 13, themeIds: [1], summary: 'Britain establishes control over Egypt.' },
  { id: 77, name: 'Sykes-Picot Agreement', year: 1916, eraId: 13, themeIds: [1], summary: 'Secret Anglo-French partition of Ottoman territories.' },
  { id: 78, name: 'Balfour Declaration', year: 1917, eraId: 13, themeIds: [1], summary: 'British support for Jewish homeland in Palestine.' },
  { id: 79, name: 'Abolition of Ottoman Caliphate', year: 1924, eraId: 13, themeIds: [1, 8], summary: 'Turkish Republic abolishes caliphate institution.' },
  { id: 80, name: 'Creation of Pakistan', year: 1947, eraId: 13, themeIds: [1], summary: 'Muslim-majority state established after Indian partition.' },
  { id: 81, name: 'Arab-Israeli War', year: 1948, eraId: 13, themeIds: [1, 5], summary: 'Conflict following creation of Israel.' },
  { id: 82, name: 'Suez Crisis', year: 1956, eraId: 13, themeIds: [1, 5], summary: 'Egypt nationalizes canal, international crisis follows.' },
  { id: 83, name: 'Six-Day War', year: 1967, eraId: 13, themeIds: [5], summary: 'Major Arab-Israeli conflict with lasting territorial changes.' },
  { id: 84, name: 'Iranian Revolution', year: 1979, eraId: 13, themeIds: [1, 8], summary: 'Islamic revolution overthrows Shah, establishes Islamic Republic.' },
  { id: 85, name: 'Soviet-Afghan War', year: 1979, eraId: 13, themeIds: [5], summary: 'Decade-long conflict with global ramifications.' },
  { id: 86, name: 'First Intifada', year: 1987, eraId: 13, themeIds: [1, 5], summary: 'Palestinian uprising against Israeli occupation.' },
  { id: 87, name: 'Ottoman Constitution', year: 1876, eraId: 10, themeIds: [1], summary: 'First constitutional government in Ottoman history.' },
  { id: 88, name: 'Young Turk Revolution', year: 1908, eraId: 13, themeIds: [1], summary: 'Constitutional movement forcing Sultan to restore parliament.' }
],

figures: [
  { id: 1, name: 'Prophet Muhammad', role: 'Prophet and Messenger', eraId: 1, born: 570, died: 632, contributions: ['Final Prophet of Islam', 'Unified Arabia', 'Established Islamic polity'], relatedIds: [1, 2, 6, 7, 8] },
  { id: 2, name: 'Abu Bakr al-Siddiq', role: 'First Caliph', eraId: 2, born: 573, died: 634, contributions: ['Close companion', 'First Caliph', 'Compiled Quran'], relatedIds: [9, 10, 11] },
  { id: 3, name: 'Umar ibn al-Khattab', role: 'Second Caliph', eraId: 2, born: 584, died: 644, contributions: ['Expanded empire', 'Administrative genius', 'Judicial reforms'], relatedIds: [12, 13, 14, 15, 16] },
  { id: 4, name: 'Uthman ibn Affan', role: 'Third Caliph', eraId: 2, born: 576, died: 656, contributions: ['Standardized Quran', 'Naval expansion', 'Infrastructure development'], relatedIds: [17, 18] },
  { id: 5, name: 'Ali ibn Abi Talib', role: 'Fourth Caliph', eraId: 2, born: 600, died: 661, contributions: ['Early convert', 'Scholar and judge', 'Eloquent speaker'], relatedIds: [18, 19, 20, 21, 22] },
  { id: 6, name: 'Khadijah bint Khuwaylid', role: 'First Believer', eraId: 1, born: 555, died: 619, contributions: ['First believer', 'Supported Prophet', 'Businesswoman'], relatedIds: [1] },
  { id: 7, name: 'Aisha bint Abi Bakr', role: 'Scholar', eraId: 1, born: 613, died: 678, contributions: ['Transmitted hadith', 'Islamic scholar', 'Teacher'], relatedIds: [7, 19] },
  { id: 8, name: 'Fatima al-Zahra', role: 'Prophet\'s Daughter', eraId: 1, born: 605, died: 632, contributions: ['Beloved daughter', 'Mother of Imams', 'Model of piety'], relatedIds: [8] },
  { id: 9, name: 'Muawiya ibn Abi Sufyan', role: 'Umayyad Founder', eraId: 3, born: 602, died: 680, contributions: ['Founded dynasty', 'Skilled administrator', 'Naval power'], relatedIds: [20, 23] },
  { id: 10, name: 'Husayn ibn Ali', role: 'Grandson of Prophet', eraId: 3, born: 626, died: 680, contributions: ['Stood for justice', 'Martyrdom at Karbala', 'Moral example'], relatedIds: [24] },
  { id: 11, name: 'Abd al-Malik ibn Marwan', role: 'Umayyad Caliph', eraId: 3, born: 646, died: 705, contributions: ['Dome of the Rock', 'Arabic administration', 'Coinage reform'], relatedIds: [25] },
  { id: 12, name: 'Tariq ibn Ziyad', role: 'Military Commander', eraId: 3, born: 670, died: 720, contributions: ['Conquered Iberia', 'Military strategist', 'Gibraltar named after him'], relatedIds: [27] },
  { id: 13, name: 'Abu Jafar al-Mansur', role: 'Abbasid Caliph', eraId: 4, born: 714, died: 775, contributions: ['Founded Baghdad', 'Consolidated Abbasid rule', 'Patron of learning'], relatedIds: [30] },
  { id: 14, name: 'Harun al-Rashid', role: 'Abbasid Caliph', eraId: 4, born: 763, died: 809, contributions: ['Golden age peak', 'Cultural flourishing', 'Legendary ruler'], relatedIds: [31] },
  { id: 15, name: 'Al-Mamun', role: 'Abbasid Caliph', eraId: 4, born: 786, died: 833, contributions: ['House of Wisdom', 'Promoted learning', 'Translation movement'], relatedIds: [31, 32] },
  { id: 16, name: 'Al-Khwarizmi', role: 'Mathematician', eraId: 4, born: 780, died: 850, contributions: ['Father of algebra', 'Algorithm named after him', 'Astronomical tables'], relatedIds: [33] },
  { id: 17, name: 'Al-Kindi', role: 'Philosopher', eraId: 4, born: 801, died: 873, contributions: ['First Arab philosopher', 'Synthesized Greek thought', 'Optics and cryptography'], relatedIds: [32] },
  { id: 18, name: 'Al-Razi', role: 'Physician', eraId: 4, born: 854, died: 925, contributions: ['Distinguished smallpox from measles', 'Medical encyclopedia', 'Clinical observation'], relatedIds: [32] },
  { id: 19, name: 'Al-Farabi', role: 'Philosopher', eraId: 4, born: 872, died: 950, contributions: ['Political philosophy', 'Logic and music', 'Synthesized Plato and Aristotle'], relatedIds: [32] },
  { id: 20, name: 'Ibn Sina (Avicenna)', role: 'Polymath', eraId: 4, born: 980, died: 1037, contributions: ['Canon of Medicine', 'Philosophy of Being', 'Influenced medieval thought'], relatedIds: [32] },
  { id: 21, name: 'Al-Biruni', role: 'Polymath', eraId: 6, born: 973, died: 1048, contributions: ['Studied India', 'Geography and astronomy', 'Comparative religion'], relatedIds: [32] },
  { id: 22, name: 'Omar Khayyam', role: 'Mathematician-Poet', eraId: 6, born: 1048, died: 1131, contributions: ['Solved cubic equations', 'Calendar reform', 'Rubaiyat poetry'], relatedIds: [32] },
  { id: 23, name: 'Al-Ghazali', role: 'Theologian', eraId: 6, born: 1058, died: 1111, contributions: ['Reconciled mysticism and law', 'Incoherence of Philosophers', 'Revived Islamic sciences'], relatedIds: [44] },
  { id: 24, name: 'Ibn Rushd (Averroes)', role: 'Philosopher', eraId: 7, born:
```